services:
  - type: web
    name: parfumdepo-bot
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py  # ИЗМЕНИТЕ НА ЭТО! НЕ GUNICORN
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
    healthCheckPath: /health
    autoDeploy: true
